# Generated by Django 4.0.2 on 2022-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('statistics', 'statistics'), ('numerical method', 'numerical method')], default='statistics', max_length=20),
        ),
    ]
