# Generated by Django 3.2.3 on 2022-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assignment_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('statistics', 'statistics'), ('NM', 'numerical method')], default='statistics', max_length=20),
        ),
    ]
