# Generated by Django 4.0.3 on 2022-03-08 13:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_assignment_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(default='', upload_to=api.models.upload_to),
        ),
    ]
